tunnel: multi-kamera
credentials-file: C:\Users\Dhimm\.cloudflared\12d14f3a-9691-401d-99f3-6ca83e917bb4.json
ingress:
  - hostname: orang.luminolynx.my.id
    service: http://localhost:5000/video/orang
  - hostname: helm.luminolynx.my.id
    service: http://localhost:5000/video/helm
  - hostname: api.luminolynx.my.id
    service: http://localhost:5000/video/api
  - hostname: masker.luminolynx.my.id
    service: http://localhost:5000/video/masker
  - service: http_status:404